### PR TITLE
Muelu eti split2

### PR DESCRIPTION
**Pull request by tawiesn**
Migrate Muelu ETI to cmake. Do not split cpp files. There is an (unsupported and not tested) flag which allows to split the cpp files.
Files from muelu-interface library are excluded from MueLu ETI and handled extra.

[Review on Reviewable](https://reviewable.io/reviews/muelu/trilinos/14)

### CODE REVIEW

**Comment by aprokop** [comment]
Reviewed 130 of 171 files at r1.
Review status: 123 of 163 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muelu/trilinos/14)*

**Comment by aprokop** [comment]
Reviewed 41 of 171 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/muelu/src/CMakeLists.txt, line 166 \[r1\]](https://reviewable.io:443/reviews/muelu/trilinos/14#-K9Y9u8MU-Af8ZDepEgt:-K9Y9u8Nu9NaDV6Tvjb5:-1435608102) ([raw file](https://github.com/muelu/trilinos/blob/5ee0a73f14b1df698130e2090e4ebfb28efb506b/packages/muelu/src/CMakeLists.txt#L166)):*
Did we ever decide on the answer on what we are going to do if Tpetra is disabled? Should we copy Tpetra's macros to MueLu?xn

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muelu/trilinos/14)*

**Comment by tawiesn** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/muelu/src/CMakeLists.txt, line 166 \[r1\]](https://reviewable.io:443/reviews/muelu/trilinos/14#-K9Y9u8MU-Af8ZDepEgt:-K9YFjw_uMf6AYd2-c-a:1135526119) ([raw file](https://github.com/muelu/trilinos/blob/5ee0a73f14b1df698130e2090e4ebfb28efb506b/packages/muelu/src/CMakeLists.txt#L166)):*
There was no "decision", yet, but i think the right approach would be to copy Tpetra's macros to MueLu. Currently, this is not important since this is the non-supported part for splitting the files. We don't need it if we do not split the cpp files (that's the ETI part far below).  I kept them separate, since there are many tiny subtle details that make it hard to merge both routines.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muelu/trilinos/14)*

**Comment by aprokop** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/muelu/src/CMakeLists.txt, line 166 \[r1\]](https://reviewable.io:443/reviews/muelu/trilinos/14#-K9Y9u8MU-Af8ZDepEgt:-K9YG_1y_C9TcBQgfl__:969332878) ([raw file](https://github.com/muelu/trilinos/blob/5ee0a73f14b1df698130e2090e4ebfb28efb506b/packages/muelu/src/CMakeLists.txt#L166)):*
OK, then simply adding a FIXME comment into the CMakeLists source should be sufficient.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/muelu/trilinos/14)*

**Pull request closed without merging**
