### PR TITLE
Xpetra refactoring - Dec7

### PR DESCRIPTION
**Pull request by tawiesn**
cleaned set of patches and reordered them a little bit. fixed some minor issues i found with different configurations on my workstation.

### CODE REVIEW

**Comment by aprokop** [comment]
Why do you hardcode EpetraNode? Why do you use wrong #ifdef checks (different from what we discussed)? All those things will have to be changed. What is the goal of these patches?

**Comment by tawiesn** [comment]
Primary goal was to add the missing specializations and have something that is still compiling. Adding the logic for the EpetraNode is one additional step in complexity. I would not add all of the complexity at once, since somehow you have to fix all the compiler and linker errors! Furthermore, I did not participate in all discussions last Friday and i am not really sure whether i understand your #ifdef checks in all details. These can be added by a simple search/replace though. If it is not working/compiling for the serial node it does not make sense to allow for OpenMP.

**Comment by aprokop** [comment]
Would not that be doing work twice, though? We would spend time testing your hardcoded version and gain some confidence in it. But then we again will refactor everything (by changing each file macros), and would have to spend the same amount of time testing.

If you have questions about the checks, I will gladly explain those to you. I want for us to get on the same page.

**Comment by tawiesn** [comment]
I don't think that we're doing work twice.
The hard-coded version is not ready for test. With testing i mean the final tests before committing using hopefully all combinations of SC, GO and NO that we can think of! But now, i am using only one or two configurations for making sure that at least the libraries are compiling and linking! I am already happy if it is working for the SerialNode with Epetra when Serial is disabled in Tpetra! Only if that is working for these one or two configurations it makes sense to add this additional logic for the OpenMP node. When this is working we can think of the systematic tests with all configurations to catch the last mistakes. 
Nevertheless, with my code changes i now have a much better understanding which guards we need in which place. One has to distinguish the guards in the Tpetra branch files and the Xpetra factories! Please find a detailed description in https://software.sandia.gov/trac/MueLu/wiki/XpetraRefactoring in the "Introduce guards in source code" section. Your proposed guards do not cover all the cases correctly even when fixing the obvious typos and missing brackets. Furthermore i think there are some more subtle details one has to be aware of (e.g. including Epetra_config.h in various places if Epetra is enabled). I would prefer to have the logic for the EptraNode typedef in one place and some kind of macro which significantly simplifies the guards. We will have these guards in quite a few places throughout Xpetra and i want to have them as simple and easy to understand as possible! Ideas and comments are always welcome!

**Pull request closed without merging**
